[package]
name = "rusty_raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
dyn-clone = "1.0.19"
image = "0.25.6"
nalgebra = "0.33.2"
rand = "0.9.0"
rayon = "1.10.0"
rlimit = "0.10.2"
stb_image = "0.3.0"
